'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {copy,type Language} from './translations';
import './gallery.css';
type Case={id:string;title:string;year:number|null;date:string;headline:string;context:string;facts:readonly (readonly [string,string])[];result:string;skills:string[];link?:string;linkLabel?:string};
function getCases(language:Language):Case[]{const c=copy[language],es=language==='es';return [
{id:'wiki',title:'WikiLearn',year:2022,date:es?'2022 → actualidad':'2022 → present',headline:c.cases.wiki[3],context:c.cases.wiki[4],facts:c.cases.wiki[5],result:es?'11 cursos digitales':'11 digital courses',skills:['learning','design','technology','systems']},
{id:'gaap',title:'GAAP / Gaplandia',year:null,date:es?'Comunidades rurales':'Rural communities',headline:c.cases.gaap[3],context:c.cases.gaap[4],facts:c.cases.gaap[5],result:es?'51 objetos de aprendizaje':'51 learning objects',skills:['learning','design','narrative']},
{id:'wayuu',title:es?'Círculos Wayuu':'Wayuu Learning Circles',year:2022,date:'2022–2024',headline:c.cases.wayuu[2],context:c.cases.wayuu[3],facts:c.cases.wayuu[4],result:es?'Formatos culturalmente relevantes':'Culturally relevant formats',skills:['learning','design','narrative','technology'],link:'https://canva.link/5y2mzgrw02a4k3q',linkLabel:c.cases.wayuu[5]},
{id:'educa',title:'ED-UCA',year:2018,date:'2018 · UCA',headline:c.origin[1],context:c.origin[2],facts:[[es?'Lo construido':'What I built',c.origin[3]]],result:es?'Biblioteca multimedia para docentes':'Multimedia library for educators',skills:['learning','design','narrative','technology'],link:'https://www.uca.edu.sv/comunicaciones-cultura/educomunicacion/',linkLabel:c.origin[4]},
{id:'humanities',title:c.more.humanities[1],year:2021,date:c.more.humanities[0],headline:es?'Una estructura que continuó más allá de su creación.':'A structure that continued beyond its creation.',context:c.more.humanities[2],facts:[],result:es?'120 estudiantes en 2021':'120 students in 2021',skills:['learning','technology','narrative']},
{id:'organizer',title:c.more.organizer[1],year:null,date:es?'Dos ediciones globales':'Two global editions',headline:es?'Contenido, plantillas y plataforma como un sistema.':'Content, templates and platform as one system.',context:c.more.organizer[2],facts:[],result:c.more.organizer[0],skills:['learning','design','technology','systems']}];}
const skillIds=['learning','design','technology','narrative','systems'];
export default function Gallery({language}:{language:Language}){
useEffect(()=>{if(window.location.hash==='#galeria'){const frame=requestAnimationFrame(()=>document.getElementById('galeria')?.scrollIntoView({behavior:'instant'}));return ()=>cancelAnimationFrame(frame)}},[]);
const es=language==='es',cases=useMemo(()=>getCases(language),[language]);
const [mode,setMode]=useState('cases'),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[active,setActive]=useState<string|null>(null);
const dialog=useRef<HTMLDialogElement>(null),closeButton=useRef<HTMLButtonElement>(null),opener=useRef<HTMLElement|null>(null);
const labels:Record<string,string>=es?{all:'Todos',learning:'Aprendizaje',design:'Diseño',technology:'Tecnología',narrative:'Narrativa',systems:'Sistemas'}:{all:'All',learning:'Learning',design:'Design',technology:'Technology',narrative:'Narrative',systems:'Systems'};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let list=cases.filter(c=>(filter==='all'||c.skills.includes(filter))&&normalize([c.title,c.headline,c.context,c.result,...c.skills.map(s=>labels[s]),...c.facts.flat()].join(' ')).includes(normalize(query)));
if(mode==='time')list=[...list].sort((a,b)=>(a.year??9999)-(b.year??9999));const current=cases.find(c=>c.id===active);
function openCase(id:string){if(!dialog.current?.open)opener.current=document.activeElement as HTMLElement;setActive(id);dialog.current?.showModal();if(dialog.current)dialog.current.scrollTop=0;closeButton.current?.focus();}
return <section className="gallery" id="galeria" aria-labelledby="gallery-title">
<div className="gallery-intro"><span className="stamp mint">{es?'GALERÍA DE SOLUCIONES':'SOLUTION GALLERY'}</span><div className="intro-grid"><h2 id="gallery-title">{es?'Hago legible':'Making complexity'}<br/><em>{es?'lo complejo.':'clear.'}</em></h2><p>{es?'Un problema puede necesitar pedagogía, diseño y tecnología a la vez. Explora los proyectos y descubre cómo se conectan esas decisiones.':'One problem can call for pedagogy, design and technology at once. Explore the projects and discover how those decisions connect.'}</p></div><p className="note">{es?'ELIGE UN CASO. SIGUE UNA CONEXIÓN. DESCUBRE OTRO.':'CHOOSE A CASE. FOLLOW A CONNECTION. DISCOVER ANOTHER.'}</p></div>
<div className="gallery-explorer"><div className="toolbar"><fieldset aria-label={es?'Forma de explorar':'Explore by'}>{[['cases',es?'01 Casos':'01 Cases'],['map',es?'02 Conexiones':'02 Connections'],['time',es?'03 Tiempo':'03 Timeline']].map(([id,label])=><button key={id} onClick={()=>setMode(id)} aria-pressed={mode===id}>{label}</button>)}</fieldset><label>{es?'Buscar un proyecto':'Find a project'}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={es?'Nombre, reto o habilidad…':'Name, challenge or skill…'}/></label></div>
<fieldset className="filters" aria-label={es?'Filtrar por conexión':'Filter by connection'}>{['all',...skillIds].map(id=><button key={id} onClick={()=>setFilter(id)} aria-pressed={filter===id}>{labels[id]}</button>)}</fieldset>
<output className="count">{list.length} {es?(list.length===1?'caso':'casos'):(list.length===1?'case':'cases')}{filter!=='all'?` · ${labels[filter]}`:''}</output>
{mode==='map'&&<div><div className="map-intro"><h3>{es?'Una práctica. Muchas conexiones.':'One practice. Many connections.'}</h3><p>{es?'Cada línea une un proyecto con una práctica descrita en su caso. Selecciona una práctica para encontrar sus proyectos.':'Each line connects a project to a practice described in its case. Select a practice to find its projects.'}</p></div><div className="network"><svg viewBox="0 0 900 480" preserveAspectRatio="none" aria-hidden="true">{list.flatMap((c,i)=>c.skills.map(s=><line key={`${c.id}-${s}`} x1="162" y1={48+skillIds.indexOf(s)*94} x2="711" y2={42+i*77} stroke="#7a5a9e" strokeWidth="2" opacity=".5"/>))}</svg><div className="nodes">{skillIds.map((s,i)=><button className="node skill" key={s} style={{left:'18%',top:`${(48+i*94)/4.8}%`}} onClick={()=>setFilter(s)} aria-pressed={filter===s}>{labels[s]}</button>)}{list.map((c,i)=><button className="node" key={c.id} style={{left:'79%',top:`${(42+i*77)/4.8}%`}} onClick={()=>openCase(c.id)}>{c.title}</button>)}</div></div></div>}
<div className={`cards ${mode==='time'?'timeline':''}`}>{list.map(c=><article className="card" key={c.id}><span className="tag">{c.skills.map(s=>labels[s]).join(' · ')}</span><h3>{c.title}</h3><p>{c.headline}</p><strong>{c.result}</strong><button onClick={()=>openCase(c.id)} aria-label={`${es?'Explorar':'Explore'} ${c.title}`}>{es?'Explorar caso':'Explore case'} ↗</button><span className="date">{c.date}{mode==='time'&&c.year===null?` · ${es?'sin fecha documentada':'date not documented'}`:''}</span></article>)}</div>
{!list.length&&<p>{es?'No hay proyectos con esa combinación.':'No projects match this combination.'} <button onClick={()=>{setFilter('all');setQuery('')}}>{es?'Limpiar filtros':'Clear filters'}</button></p>}</div>
<dialog ref={dialog} aria-labelledby="gallery-case-title" onClose={()=>{setActive(null);opener.current?.focus()}}><button className="close" ref={closeButton} onClick={()=>dialog.current?.close()} aria-label={es?'Cerrar caso':'Close case'}>{es?'Cerrar':'Close'} ×</button>{current&&<><span className="tag">{current.date}</span><h2 id="gallery-case-title">{current.title}</h2><p><b>{current.headline}</b></p><p>{current.context}</p><dl>{current.facts.map(([term,description])=><div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl><p><strong>{current.result}</strong></p>{current.link&&<p><a href={current.link} target="_blank" rel="noreferrer">{current.linkLabel} ↗</a></p>}<h3>{es?'Conecta con':'Connects with'}</h3><p>{current.skills.map(s=>labels[s]).join(' · ')}</p><div className="related">{cases.filter(c=>c.id!==current.id&&c.skills.some(s=>current.skills.includes(s))).slice(0,3).map(c=><button key={c.id} onClick={()=>openCase(c.id)}>{c.title} →</button>)}</div><p className="source">{es?'Estas conexiones muestran prácticas compartidas entre proyectos.':'These connections show practices shared across projects.'}</p></>}</dialog>
</section>;
}
